// Processor partner configs — exact rates from signed agreements
// ES module (project uses "type": "module")

const processors = {
  kurv: {
    name: "Kurv (EMS)",
    residual_split: 0.80,
    merchant_type: "retail",
    costs: {
      interchange: "pass_through",
      bin_sponsorship_percent: 0.0002,       // 0.02% of volume
      auth_fee_bank_card_ip: 0.04,           // per transaction
      auth_fee_voice: 0.60,
      auth_fee_ems_plus: 0.10,
      auth_fee_other_including_amex: 0.05,
      avs_fee: 0.01,                         // per transaction
      batch_fee: 0.05,                       // per batch (assume 30/month)
      monthly_access_fee: 6.00,
      monthly_minimum: 0,
      debit_access_fee: 0,
      platinum_club: 5.00,
      semi_annual_tech_compliance: 10.00,    // billed every 6 months per MID → $1.67/mo
      monthly_breach_protection: 6.00,       // 50% split on this item
      pin_debit_ebt_per_txn: 0.05,
      online_reporting: 0,
      application_fee: 0,
      reprogram_fee: 0,
      setup_fee: 0,
    },
    risk_merchants: {
      residual_split: 0.50,
      auth_fee: 0.06,
      bin_sponsorship_percent: 0.001,
      monthly_access_fee: 8.00,
      monthly_breach_protection: 8.00,
      sponsor_fee_percent: 0.002,
      sponsor_fee_per_txn: 0.20,
    },
    gateway: {
      convenue_pay_auth: 0.04,
      convenue_pay_monthly: 4.00,
      e_invoicing_auth: 0.04,
      account_updater_auth: 0.25,
      account_updater_monthly: 25.00,
      level3_auth: 0.25,
      level3_monthly: 25.00,
      tokenization_per_record: 0.04,
    },
    pos: {
      total_touch_monthly_saas: 59.95,
    },
    bonuses: {
      activation_bonus: 0,
      multiplier: 0,
      fast_track_bonus: 0,
    },
    notes: [
      "80% residual split on ALL retail merchants",
      "Residuals lifetime vested per Section 5.3",
      "Non-exclusive — can work with other processors",
      "Non-solicitation — cannot move Kurv merchants to another processor",
      "5 sponsor banks: Axiom, Merrick, BMO Harris, Esquire, Central Bank of St. Louis",
      "If residual under $100/month after one year, Kurv can stop paying",
      "3 year term with auto-renewal",
      "Can sell book of business with right of first refusal to Kurv",
    ],
  },

  epi: {
    name: "Electronic Payments Inc (EPI)",
    tiers: {
      option_a: {
        name: "Option A — Major Merchant Micro Pricing",
        residual_split: 0.50,
        auth_fee_cygma: 0.00,               // ZERO auth fee
        auth_fee_fiserv: 0.015,
        tsys_surcharge: 0.025,
        amex_optblue_percent: 0.001,        // 0.10%
        cbd_bin_percent: 0.001,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        platform_admin_monthly: 1.75,
        activation_bonus: 300,
        multiplier: 1,
        multiplier_cap: 500,
        free_terminal: true,
        exatouch_placement: true,
      },
      option_b: {
        name: "Option B — 6x Multiplier",
        residual_split: 0.50,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.025,
        auth_fee_fiserv: 0.025,
        tsys_surcharge: 0.025,
        amex_optblue_percent: 0.0015,       // 0.15%
        amex_optblue_placement_percent: 0.003,
        cbd_bin_percent: 0.0015,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 1.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 0.95,
        activation_bonus: 300,
        multiplier: 6,
        multiplier_cap: 1500,
        free_terminal: true,
        exatouch_placement: true,
      },
      option_c: {
        name: "Option C — POS Placement",
        residual_split: 0.50,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.025,
        auth_fee_fiserv: 0.025,
        tsys_surcharge: 0.025,
        amex_optblue_percent: 0.0015,
        amex_optblue_placement_percent: 0.003,
        cbd_bin_percent: 0.0015,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 1.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 0.95,
        activation_bonus: 500,
        multiplier: 0,
        free_terminal: true,
        exatouch_placement: true,
      },
      option_d: {
        name: "Option D — 3x Multiplier",
        residual_split: 0.65,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.025,
        auth_fee_fiserv: 0.025,
        tsys_surcharge: 0.025,
        amex_optblue_percent: 0.0015,
        cbd_bin_percent: 0.0015,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 1.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 0.95,
        activation_bonus: 300,
        multiplier: 3,
        multiplier_cap: 750,
        free_terminal: true,
        exatouch_placement: true,
      },
      option_e: {
        name: "Option E — ISO + Sub-Agent",
        residual_split: 0.80,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.035,
        auth_fee_fiserv: 0.035,
        tsys_surcharge: 0.015,
        amex_optblue_percent: 0.0015,
        cbd_bin_percent: 0.0015,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 3.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 1.95,
        activation_bonus: 200,
        multiplier: 0,
        free_terminal: false,
        exatouch_placement: true,
      },
      option_f: {
        name: "Option F — BYOD",
        residual_split: 0.90,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.04,
        auth_fee_fiserv: 0.04,
        tsys_surcharge: 0.015,
        amex_optblue_percent: 0.002,
        cbd_bin_percent: 0.002,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 4.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 2.95,
        activation_bonus: 0,
        multiplier: 0,
        free_terminal: false,
        exatouch_placement: true,
      },
    },
    fast_track_bonus: 15000,               // 30 approved deals in first 90 days
    statement_fee_required: 5.00,
    monthly_minimum_required: 25.00,
    etf_waiver_disqualifies_multiplier: true,
    bonus_clawback_months: 12,
    notes: [
      "Pick any tier for any deal — can mix and match",
      "Statement fee of $5.00 and $25 monthly minimum required for all bonuses",
      "Waiving ETF disqualifies multiplier bonuses",
      "Bonuses clawed back if merchant closes within 12 months",
      "$15,000 fast track bonus for 30 deals in first 90 days",
      "Residual advance available at Prime + 8-12% once earning $5k+/month",
    ],
  },
};

export default processors;
