// Processor partner configs — exact rates from signed agreements
// ES module (project uses "type": "module")

const processors = {
  kurv: {
    name: "Kurv (EMS)",
    residual_split: 0.80,
    merchant_type: "retail",
    costs: {
      interchange: "pass_through",
      bin_sponsorship_percent: 0.0002,       // 0.02% of volume
      auth_fee_bank_card_ip: 0.04,           // per transaction
      auth_fee_voice: 0.60,
      auth_fee_ems_plus: 0.10,
      auth_fee_other_including_amex: 0.05,
      avs_fee: 0.01,                         // per transaction
      batch_fee: 0.05,                       // per batch (assume 30/month)
      monthly_access_fee: 6.00,
      monthly_minimum: 0,
      debit_access_fee: 0,
      platinum_club: 5.00,
      semi_annual_tech_compliance: 10.00,    // billed every 6 months per MID → $1.67/mo
      monthly_breach_protection: 6.00,       // 50% split on this item
      pin_debit_ebt_per_txn: 0.05,
      online_reporting: 0,
      application_fee: 0,
      reprogram_fee: 0,
      setup_fee: 0,
    },
    risk_merchants: {
      residual_split: 0.50,
      auth_fee: 0.06,
      bin_sponsorship_percent: 0.001,
      monthly_access_fee: 8.00,
      monthly_breach_protection: 8.00,
      sponsor_fee_percent: 0.002,
      sponsor_fee_per_txn: 0.20,
    },
    gateway: {
      convenue_pay_auth: 0.04,
      convenue_pay_monthly: 4.00,
      e_invoicing_auth: 0.04,
      account_updater_auth: 0.25,
      account_updater_monthly: 25.00,
      level3_auth: 0.25,
      level3_monthly: 25.00,
      tokenization_per_record: 0.04,
    },
    pos: {
      total_touch_monthly_saas: 59.95,
    },
    bonuses: {
      activation_bonus: 0,
      multiplier: 0,
      fast_track_bonus: 0,
    },
    notes: [
      "80% residual split on ALL retail merchants",
      "Residuals lifetime vested per Section 5.3",
      "Non-exclusive — can work with other processors",
      "Non-solicitation — cannot move Kurv merchants to another processor",
      "5 sponsor banks: Axiom, Merrick, BMO Harris, Esquire, Central Bank of St. Louis",
      "If residual under $100/month after one year, Kurv can stop paying",
      "3 year term with auto-renewal",
      "Can sell book of business with right of first refusal to Kurv",
    ],
  },

  epi: {
    name: "Electronic Payments Inc (EPI)",
    tiers: {
      option_a: {
        name: "Option A — Major Merchant Micro Pricing",
        residual_split: 0.50,
        auth_fee_cygma: 0.00,               // ZERO auth fee
        auth_fee_fiserv: 0.015,
        tsys_surcharge: 0.025,
        amex_optblue_percent: 0.001,        // 0.10%
        cbd_bin_percent: 0.001,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        platform_admin_monthly: 1.75,
        activation_bonus: 300,
        multiplier: 1,
        multiplier_cap: 500,
        free_terminal: true,
        exatouch_placement: true,
      },
      option_b: {
        name: "Option B — 6x Multiplier",
        residual_split: 0.50,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.025,
        auth_fee_fiserv: 0.025,
        tsys_surcharge: 0.025,
        amex_optblue_percent: 0.0015,       // 0.15%
        amex_optblue_placement_percent: 0.003,
        cbd_bin_percent: 0.0015,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 1.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 0.95,
        activation_bonus: 300,
        multiplier: 6,
        multiplier_cap: 1500,
        free_terminal: true,
        exatouch_placement: true,
      },
      option_c: {
        name: "Option C — POS Placement",
        residual_split: 0.50,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.025,
        auth_fee_fiserv: 0.025,
        tsys_surcharge: 0.025,
        amex_optblue_percent: 0.0015,
        amex_optblue_placement_percent: 0.003,
        cbd_bin_percent: 0.0015,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 1.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 0.95,
        activation_bonus: 500,
        multiplier: 0,
        free_terminal: true,
        exatouch_placement: true,
      },
      option_d: {
        name: "Option D — 3x Multiplier",
        residual_split: 0.65,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.025,
        auth_fee_fiserv: 0.025,
        tsys_surcharge: 0.025,
        amex_optblue_percent: 0.0015,
        cbd_bin_percent: 0.0015,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 1.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 0.95,
        activation_bonus: 300,
        multiplier: 3,
        multiplier_cap: 750,
        free_terminal: true,
        exatouch_placement: true,
      },
      option_e: {
        name: "Option E — ISO + Sub-Agent",
        residual_split: 0.80,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.035,
        auth_fee_fiserv: 0.035,
        tsys_surcharge: 0.015,
        amex_optblue_percent: 0.0015,
        cbd_bin_percent: 0.0015,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 3.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 1.95,
        activation_bonus: 200,
        multiplier: 0,
        free_terminal: false,
        exatouch_placement: true,
      },
      option_f: {
        name: "Option F — BYOD",
        residual_split: 0.90,
        bin_sponsorship_percent: 0.0002,
        auth_fee_cygma: 0.04,
        auth_fee_fiserv: 0.04,
        tsys_surcharge: 0.015,
        amex_optblue_percent: 0.002,
        cbd_bin_percent: 0.002,
        high_risk_bin_percent: 0.0005,
        pin_debit_ebt_auth: 0.04,
        avs_fee: 0.015,
        account_on_file_monthly: 5.00,
        platform_admin_monthly: 4.75,
        chargeback_fee: 12.50,
        retrieval_fee: 5.00,
        pci_compliance_monthly: 4.95,
        regulatory_compliance_monthly: 2.95,
        activation_bonus: 0,
        multiplier: 0,
        free_terminal: false,
        exatouch_placement: true,
      },
    },
    fast_track_bonus: 15000,               // 30 approved deals in first 90 days
    statement_fee_required: 5.00,
    monthly_minimum_required: 25.00,
    etf_waiver_disqualifies_multiplier: true,
    bonus_clawback_months: 12,
    notes: [
      "Pick any tier for any deal — can mix and match",
      "Statement fee of $5.00 and $25 monthly minimum required for all bonuses",
      "Waiving ETF disqualifies multiplier bonuses",
      "Bonuses clawed back if merchant closes within 12 months",
      "$15,000 fast track bonus for 30 deals in first 90 days",
      "Residual advance available at Prime + 8-12% once earning $5k+/month",
    ],
  },
  beacon: {
    name: "Beacon Payments",
    platforms: {
      cardconnect: {
        name: "CardConnect",
        residual_split: 0.60,
        costs: {
          interchange: "pass_through",
          bin_sponsorship_percent: 0.0001,       // 0.01%
          auth_fee_bankcard: 0.03,
          auth_fee_non_bankcard: 0.03,
          pin_debit_ebt_per_txn: 0.03,
          avs_fee: 0.03,
          batch_fee: 0.03,
          voice_auth: 0.75,
          amex_optblue_interchange: "pass_through",
          amex_optblue_bin_sponsorship: 0.001,   // 0.10%
          monthly_minimum: 0,
          statement_fee: 0,
          transarmor_monthly: 5.00,
          clover_platform_monthly: 5.00,
          monthly_platform_fee: 5.00,
        },
      },
      tsys_payarc: {
        name: "TSYS Payarc",
        residual_split: 0.60,
        costs: {
          interchange: "pass_through",
          bin_sponsorship_percent: 0.0001,       // 0.01%
          auth_fee: 0.03,
          auth_fee_wireless: 0.10,
          edc_transaction_fee: 0.00,
          debit_ebt_per_item: 0.03,
          amex_optblue: 0.001,                   // 0.10%
          avs_fee: 0.03,
          voice_auth: 0.55,
          monthly_customer_service: 5.00,
          monthly_statement_fee: 0,
          monthly_tax_filing: 0,
          debit_monthly_access: 0,
          chargeback_fee: 10.00,
          retrieval_fee: 7.50,
          chargeback_arbitration: 25.00,
          batch_close_fee: 0.03,
          ach_unauthorized_return: 25.00,
          pci_compliance_monthly: 5.59,
          pci_non_validation_monthly: 29.95,     // after 60 days if not compliant
          proactive_security_fee: 49.95,         // after 180 days if not compliant
        },
      },
    },
    bonuses: {
      advance_per_account: 1000,    // paid after 2 closed batches
      advance_reduced: 150,         // if missing $10 monthly fee or $30 minimum
      multiplier: 8,                // 8x first month residual
      multiplier_cap: 5000,
      multiplier_floor: 150,
      clawback_days: 365,
      requires_monthly_fee: 10.00,
      requires_monthly_minimum: 30.00,
    },
    flex_sell_pos: {
      residual_split: 0.50,
      no_bonus: true,
      tiers_dual_pricing: [
        { min_volume: 15000, max_volume: 25000, equipment: "Free Handheld or Mini POS" },
        { min_volume: 25000, max_volume: 40000, equipment: "1 Free POS station" },
        { min_volume: 40000, max_volume: 60000, equipment: "2 Free POS stations" },
        { min_volume: 60000, max_volume: null,  equipment: "Approval required" },
      ],
    },
    contract_term_years: 3,
    non_exclusive: true,
    residuals_survive_termination: true,
    residual_minimum_threshold: 1000,   // $1,000 CUMULATIVE total (not monthly) — Beacon can stop paying once this is exceeded if terminated
    non_solicitation_penalty: "39x average monthly gross fees",
    can_sell_book: true,
    right_of_last_refusal: true,
    notes: [
      "60% residual split on CardConnect platform",
      "$1,000 advance per activated account (2 closed batches required)",
      "8x multiplier on first month residual, capped at $5,000",
      "Advance reduced to $150 if merchant missing $10 monthly fee or $30 minimum",
      "Flex Sell POS program at 50% split with free equipment but no bonus",
      "BIN sponsorship at 0.01% — lowest of all three processors",
      "Non-exclusive, 3-year term, residuals survive termination",
      "Non-solicitation penalty: 39x average monthly gross fees per merchant",
      "Supports Clover POS with $5/month platform fee",
      "Alternative platform (TSYS/Payarc) available for different merchant types",
    ],
  },
};

export const posCompatibility = {
  kurv: {
    supported_terminals: ['pax', 'dejavoo', 'verifone', 'ingenico'],
    proprietary_pos: 'MaxxPay (Mini, Pro, Premier)',
    restaurant_pos: 'Total Touch ($59.95/month)',
    supports_clover: false,
    supports_reprogram: true,
    free_terminal_available: true,
    free_pos_available: true,
    notes: 'MaxxPay line competes with Clover. Total Touch for restaurants. Can reprogram most standalone terminals.',
  },
  epi: {
    supported_terminals: ['pax', 'dejavoo', 'verifone', 'ingenico'],
    proprietary_pos: 'Exatouch',
    restaurant_pos: 'Exatouch (free placement on Option C)',
    supports_clover: false,
    supports_reprogram: true,
    free_terminal_available: true,
    free_pos_available: true,
    notes: 'Exatouch is their in-house POS. Free placement available on Option C at 50% split. Can reprogram most standalone terminals.',
  },
  beacon: {
    supported_terminals: ['pax', 'dejavoo', 'verifone', 'ingenico', 'clover'],
    proprietary_pos: null,
    restaurant_pos: 'Clover (through Flex Sell program)',
    supports_clover: true,
    supports_reprogram: true,
    free_terminal_available: true,
    free_pos_available: true,
    clover_platform_fee: 5.00,
    flex_sell_split: 0.50,
    flex_sell_bonus: false,
    notes: 'Only processor that natively supports Clover. Flex Sell program provides free Clover at 50% split with no bonus. Can also reprogram standalone terminals.',
  },
};

export const posLockStatus = {
  clover:           { locked: false, compatible_processors: ['beacon'],              notes: 'Clover hardware works with Beacon via CardConnect. Kurv and EPI cannot process through Clover.' },
  square:           { locked: true,  compatible_processors: [],                      notes: 'Locked to Square processing. Must switch hardware entirely.' },
  toast:            { locked: true,  compatible_processors: [],                      notes: 'Locked to Toast processing. Must switch hardware entirely.' },
  pax:              { locked: false, compatible_processors: ['kurv', 'epi', 'beacon'], notes: 'Can be reprogrammed to any processor. No hardware change needed.' },
  dejavoo:          { locked: false, compatible_processors: ['kurv', 'epi', 'beacon'], notes: 'Can be reprogrammed to any processor. No hardware change needed.' },
  verifone:         { locked: false, compatible_processors: ['kurv', 'epi', 'beacon'], notes: 'Can be reprogrammed to any processor. No hardware change needed.' },
  ingenico:         { locked: false, compatible_processors: ['kurv', 'epi', 'beacon'], notes: 'Can be reprogrammed to any processor. No hardware change needed.' },
  heartland_genius: { locked: true,  compatible_processors: [],                      notes: 'Locked to Global Payments/Heartland processing. Must switch hardware entirely or negotiate with Heartland directly.' },
  spoton:           { locked: true,  compatible_processors: [],                      notes: 'Locked to SpotOn processing. Must switch hardware entirely.' },
  lightspeed:       { locked: true,  compatible_processors: [],                      notes: 'Locked to Lightspeed processing. Must switch hardware entirely.' },
  revel:            { locked: false, compatible_processors: ['beacon'],              notes: 'Semi-open system. May work with some processors. Verify before committing.' },
  shopify_pos:      { locked: true,  compatible_processors: [],                      notes: 'Locked to Shopify Payments. Must switch hardware entirely.' },
  stripe_terminal:  { locked: true,  compatible_processors: [],                      notes: 'Locked to Stripe processing. Must switch hardware entirely.' },
  ncr_aloha:        { locked: true,  compatible_processors: [],                      notes: 'Locked to NCR/Aloha processing. Complex migration required.' },
  micros_oracle:    { locked: true,  compatible_processors: [],                      notes: 'Locked to Oracle processing. Complex migration required.' },
  standalone_unknown: { locked: false, compatible_processors: ['kurv', 'epi', 'beacon'], notes: 'Most standalone terminals can be reprogrammed. Verify brand before committing.' },
  online_only:      { locked: false, compatible_processors: ['kurv', 'epi', 'beacon'], notes: 'E-commerce merchant. All processors support payment gateway integration.' },
  other:            { locked: false, compatible_processors: [],                      notes: 'Unknown POS system. Verify compatibility before recommending a processor.' },
};

export default processors;
